run:
  tests: false
  issues-exit-code: 1
  timeout: 3m

severity:
  default-severity: minor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    #- depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    #- gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - err113
    - gofumpt
    - goimports
    - gosec
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - revive
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/dreamscached/minequery
  revive:
    rules:
      - name: add-constant
        arguments:
          - allowStrs: '"","udp"'
            allowInts: "0,1,2,512"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [10]
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        arguments: [9]
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
        arguments: [sayRepetitiveInsteadOfStutters]
      - name: flag-parameter
      - name: function-result-limit
        arguments: [3]
      - name: function-length
        arguments: [40, 0]
      - name: get-return
      - name: identical-branches
        severity: error
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: import-shadowing
      - name: line-length-limit
        arguments: [120]
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: optimize-operands-order
      - name: package-comments
      - name: range
      - name: range-val-in-closure
      - name: range-val-address
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
        severity: error
      - name: struct-tag
        severity: error
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      #- name: use-any # Go 1.13 compatibility
      - name: useless-break
      - name: waitgroup-by-value
  gofumpt:
    extra-rules: true
  makezero:
    always: true
  varnamelen:
    max-distance: 20
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names: [err, ctx]
  misspell:
    locale: US
    ignore-words: []
    